# the prefix for the environment variables to configure the script
# e.g. "cores" becomes "builder_cores" so that you can start it with
#     $ export builder_cores=2
env_prefix: builder_

# the number of cores used to build the image
cores: 2

# if there should be a lot of output
debug: true

firmware:
    # where should we clone the firmware to?
    directory: "./firmware"
    # default repository to clone
    repository:
        git_url: "https://github.com/freifunk-berlin/firmware.git"
        branch: "daily/upstream-master"
        depth: 1

results:
    # this is the path where the results of the build occur
    source: "./firmware/firmwares"
    # this is where they are copied to after a successful build
    # it allows serving the packages and downloading
    target: "./firmwares"

# files to modify
files: []
# directories in which files can be placed
allowed_directories:
- "/packages/"
- "/configs/"
- "/profiles/"

# the email to send a notification to
email: null

# the build defaults
# see https://github.com/freifunk-berlin/firmware/blob/master/config.mk
build:
    # the build target
    target: ar71xx-generic
    # list of packages to use
    # see config.mk
    package_list:
    - default
    # the format of the build id
    id_format: "%Y-%m-%d_%H-%M-%S"
    # something you do not need to configure
    # it is used internally
    id: "0000-00-00_00-00-00"
    status: "unkonwn"
    # file to save config to in build directory
    result: config.json

# this is set by the request's host header
host: "localhost:5000"

# this is the configuration which is not usedbut sent by the client
remaining_config: null

